server:
  port: 8081

spring:
  datasource:
    # 建议保留 createDatabaseIfNotExist，首次启动自动建库
    url: jdbc:mysql://127.0.0.1:3306/learn?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
    # 如有 schema.sql / data.sql，启用自动执行；没有就删掉这段
  sql:
    init:
      mode: always
  devtools:
    restart:
      enabled: true              # 开启重启（默认开发环境已开启）
      poll-interval: 2s          # 扫描间隔（可调）
      quiet-period: 1s           # 静默期（可调）
      # additional-paths: src/main/java,src/main/resources  # 如需额外监控其它目录可以加
      # exclude: "static/**,public/**,templates/**"         # 如需排除可配置
    livereload:
      enabled: true              # 前端资源改动时通知浏览器（需装 LiveReload 插件）

logging:
  level:
    org.springframework.boot.devtools: DEBUG # 打印 SQL 绑定参数可改成 DEBUG
