server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 如有 schema.sql / data.sql，启用自动执行；没有就删掉这段
  sql:
    init:
      mode: never

mybatis-plus:
  # 控制台打印 SQL（学习阶段很有用）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 明确 XML 扫描路径（也可不写，starter 默认会扫 classpath*:/mapper/**/*.xml）
  mapper-locations: classpath*:mapper/*.xml

app:
  jwt:
    secret: "change-this-to-a-long-random-secret-please"
    expireMinutes: 120
